version: '3'
services:
	# Base de datos mariadb
    db:
        image: mariadb
        container_name: mariadb
        networks:
         - net
        environment:
         # Nombre de la base de datos de uso
         - MYSQL_DATABASE=${MYSQL_DATABASE}
         # Nombre de usuario de acceso
         - MYSQL_USER=${MYSQL_USER}
         # Contrase침a de acceso
         - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
         # Contrase침a de acceso del usuario administrador
         - MYSQL_ROOT_PASSWORD=$(openssl aes-256-cbc -e -k "my_secret_key" -in mysql_root_password.txt -out mysql_root_password.txt.enc)
        volumes:
         - db_data:/var/lib/mysql
        secrets:
         - mysql_password
         - mysql_root_password
    sops:
        image: mozilla/sops:latest
        command: ["sops", "--config", "/secrets/sops.yaml", "--decrypt", "/secrets/mysecrets.enc.yaml"]
        volumes:
          - "/secrets:/secrets"
        environment:
          SOPS_PGP_PRIVATE_KEY: /secrets/myprivatekey.asc
        secrets:
          - mysecrets
            external: true
# Definici칩n de secretos que almacenan las contrase침as de acceso
secrets:
    mysql_root_password:     
        file: mysql_root_password.txt.enc
volumes:
    db_data: