apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-jlil
  labels:
    app: jlil
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: jlil
  template:
    metadata:
      labels:
        app: jlil
    spec:
      containers:
      - image: iesgn/test_web:latest
        name: contenedor-jlil
        ports:
        - name: http
          containerPort: 80