apiVersion: apps/v1
kind: Deployment
metadata:
  name: version1-jlil
  labels:
    app: jlil-1
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: jlil-1
  template:
    metadata:
      labels:
        app: jlil-1
    spec:
      containers:
      - image: iesgn/test_web:version2
        name: contenedor-jlil-version1
        ports:
        - name: http
          containerPort: 80