version: '3.8'

services:
  # Contenedor de claves vault
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    restart: unless-stopped  
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      #VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - vault-data:/vault/file
      - vault-config:/vault/config
      - secrets:/secrets
    cap_add:
      - IPC_LOCK
    command: ["server", "-dev", "-dev-root-token-id=root"]
    networks:
      - net
  # Base de datos mariadb
  db:
    image: mariadb
    container_name: mariadb
    networks:
      - net
    environment:
      # Nombre de la base de datos de uso
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # Nombre de usuario de acceso
      - MYSQL_USER=${MYSQL_USER}
      # Contraseña de acceso
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # Contraseña de acceso del usuario administrador
      - MYSQL_ROOT_PASSWORD_FILE={{ with secret "mysql_credentials" }}{{ .Data.root_password }}{{ end }}
      - VAULT_ROLE_ID=db1b8513-7d49-af6f-2788-911eebeb81a2
    volumes:
      - db_data:/var/lib/mysql
    #secrets:
      #- mariadb_credentials
  # Interfaz web para gestionar el servidor de bases de datos mariadb
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    networks:
      - net
    environment:
      # Permite el acceso arbitrario al contenedor de mariadb
      - PMA_ARBITRARY=1

#secrets:
  #mariadb_credentials:

networks:
  net:

volumes:
  vault-data:
  vault-config:
  db_data:
  secrets:
            