version: '2'
services:
  mariadb:
    container_name: mariadbPepe
    hostname: mariadbPepe
    image: docker.io/bitnami/mariadb:11.1
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=PEPE
      - MARIADB_PASSWORD=PEPE
      - MARIADB_DATABASE=DB_PEPE
    networks:
      redRedminePepe:
        ipv4_address: 192.168.22.22
  redmine:
    container_name: redminePepe
    hostname: redminePepe
    image: docker.io/bitnami/redmine:5
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadbPepe
      - REDMINE_DATABASE_USER=PEPE
      - REDMINE_DATABASE_PASSWORD=PEPE
      - REDMINE_DATABASE_NAME=DB_PEPE
      - REDMINE_USERNAME=PEPE
      - REDMINE_PASSWORD=PEPE
    networks:
      redRedminePepe:
        ipv4_address: 192.168.22.23
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
networks:
  redRedminePepe:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.22.0/24
