apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: replicaset-test-web-jpo
spec:
    replicas: 3
    selector:
        matchLabels:
            app: test-web-jpo
    template:
        metadata:
            labels:
                app: test-web-jpo
        spec:
            containers:
                - image: iesgn/test_web:latest
                  name: contenedor-test-web-jpo